import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
        <div>
            <ul className="menu menu-vertical lg:menu-horizontal bg-base-200 rounded-box">
                <li><Link  href={`/list`} >List</Link></li>
                <li><Link  href={`/product?pid=25591139M`} >Paisley Shirt</Link></li>
                <li><Link  href={`/product?pid=25518484M`} >Striped Shirt</Link></li>
            </ul>
        </div >
        <div className={inter.className}>
          {children}
        </div>
        </>
  );
}
